import { useCallback, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import "../../styles/admin/AdminDashboard.css";
import "../../styles/admin/Reports.css";
import { useLogPageView } from "../../lib/useLogPageView";
import Sidebar from "../../components/Sidebar";

const PAGE_SIZE = 15;

const formatDateTime = (isoString) => {
  if (!isoString) return "—";
  const d = new Date(isoString);
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(
    d.getHours()
  )}:${pad(d.getMinutes())}`;
};

const formatDate = (isoString) => {
  if (!isoString) return "—";
  const d = new Date(isoString);
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

const Reports = () => {
  useLogPageView("Viewed Reports");

  const [reports, setReports] = useState([]);
  const [creators, setCreators] = useState([]);
  const [creatorId, setCreatorId] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [page, setPage] = useState(1);
  const [totalCount, setTotalCount] = useState(0);

  const totalPages = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));

  const fetchReports = useCallback(async () => {
    setLoading(true);
    setError("");

    const from = (page - 1) * PAGE_SIZE;
    const to = from + PAGE_SIZE - 1;

    let query = supabase
      .from("reports")
      .select(
        `id, generated_by, report_name, parameters, format, status, date_range_start, date_range_end, created_at,
         profiles ( full_name )`,
        { count: "exact" }
      );
    if (creatorId) query = query.eq("generated_by", creatorId);
    const { data, error: fetchError, count } = await query
      .order("created_at", { ascending: false })
      .range(from, to);

    if (fetchError) {
      setError("Could not load reports.");
    } else {
      setReports(data || []);
      setTotalCount(count || 0);
    }
    setLoading(false);
  }, [page, creatorId]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  useEffect(() => {
    supabase
      .from("profiles")
      .select("id, full_name")
      .order("full_name")
      .then(({ data }) => setCreators(data || []));
  }, []);

  return (
    <div className="admin-shell">
      <Sidebar />

      <main className="admin-main">
        <header className="page-header">
          <h1>Reports</h1>
          <p>Review report history across all accounts</p>
        </header>

        <section className="panel">
          <h2>Report History</h2>

          <div className="reports-filter-bar">
            <label htmlFor="report-creator-filter">Generated by</label>
            <select
              id="report-creator-filter"
              value={creatorId}
              onChange={(event) => {
                setPage(1);
                setCreatorId(event.target.value);
              }}
            >
              <option value="">All creators</option>
              {creators.map((creator) => (
                <option key={creator.id} value={creator.id}>
                  {creator.full_name || "Unnamed account"}
                </option>
              ))}
            </select>
          </div>

          {loading && <p>Loading reports...</p>}
          {error && <p style={{ color: "#d64545" }}>{error}</p>}

          {!loading && !error && (
            <>
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Report</th>
                      <th>Generated At</th>
                      <th>Generated By</th>
                      <th>Date Range</th>
                      <th>Parameters</th>
                      <th>Format</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reports.length === 0 && (
                      <tr>
                        <td colSpan={7}>{creatorId ? "No reports match this creator." : "No reports have been generated yet."}</td>
                      </tr>
                    )}
                    {reports.map((row) => (
                      <tr key={row.id}>
                        <td>{row.report_name || "Untitled report"}</td>
                        <td>{formatDateTime(row.created_at)}</td>
                        <td>{row.profiles?.full_name || "—"}</td>
                        <td className="data-cell">
                          {formatDate(row.date_range_start)} – {formatDate(row.date_range_end)}
                        </td>
                        <td>{row.parameters?.join(", ") || "All parameters"}</td>
                        <td>{row.format?.toUpperCase() || "PDF"}</td>
                        <td>
                          {row.status === "success" ? (
                            <span className="badge badge-normal">✓ Success</span>
                          ) : (
                            <span className="badge badge-failed">× Failed</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {totalPages > 1 && (
                <div className="um-pagination">
                  <button disabled={page === 1} onClick={() => setPage((p) => p - 1)}>
                    ‹
                  </button>
                  <span style={{ fontSize: "0.82rem", color: "var(--color-text-muted)" }}>
                    Page {page} of {totalPages}
                  </span>
                  <button
                    disabled={page === totalPages}
                    onClick={() => setPage((p) => p + 1)}
                  >
                    ›
                  </button>
                </div>
              )}
            </>
          )}
        </section>
      </main>
    </div>
  );
};

export default Reports;